services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=0
      - LS_LOG=warn
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  airflow:
    image: apache/airflow:2.9.2-python3.11
    container_name: airflow
    command: standalone
    env_file:
      - ../.env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=UTC
      - S3_ENDPOINT_URL=http://localstack:4566
      # install libs inside the Airflow image
      - AIRFLOW_PIP_ADDITIONAL_REQUIREMENTS=boto3 requests pandas pyarrow
      # for Hadoop libs that occasionally peek at OS user:
      - HADOOP_USER_NAME=airflow
      - JAVA_TOOL_OPTIONS=-Duser.name=airflow
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - "../airflow/dags:/opt/airflow/dags"
      - "../airflow/plugins:/opt/airflow/plugins"
      - "../.env:/opt/airflow/.env:ro"

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=true
      # Make sure the Hadoop layer stays in "simple" (no Kerberos)
      - JAVA_TOOL_OPTIONS=-Duser.name=airflow
    ports:
      - "7077:7077"
      - "8081:8080"
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - "../spark/jobs:/opt/spark_jobs:ro"
      - "../spark/conf/core-site.xml:/opt/bitnami/spark/conf/core-site.xml:ro"

  spark-worker-1:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - JAVA_TOOL_OPTIONS=-Duser.name=airflow
    depends_on:
      - spark-master
    volumes:
      - "../spark/conf/core-site.xml:/opt/bitnami/spark/conf/core-site.xml:ro"